### ISSUE TITLE
FileNotFoundError: Could not find module 'D:\Anaconda3\envs\geometric\Lib\site-packages\torch_sparse\_convert.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by aminemosbah** [thinng/GraphDTA#7]
(geometric) D:\Anaconda3\envs\geometric\GraphDTA>python create_data.py
Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from utils import *
  File "D:\Anaconda3\envs\geometric\GraphDTA\utils.py", line 5, in <module>
    from torch_geometric.data import InMemoryDataset, DataLoader
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_sparse\__init__.py", line 12, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch\_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "D:\Anaconda3\envs\geometric\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Anaconda3\envs\geometric\Lib\site-packages\torch_sparse\_convert.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by thinng** [comment]
Please follow the steps. Seems you have not created 'geometric' environment.

**Comment by aminemosbah** [comment]
hi sir,
i created 'geometric' environment and downloaded all requirements
then activated the env but still the same error.
seems to me it's a PATH issue? 
(geometric) D:\Anaconda3\envs\geometric>conda activate geometric

(geometric) D:\Anaconda3\envs\geometric>python create_data.py
Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from utils import *
  File "D:\Anaconda3\envs\geometric\utils.py", line 5, in <module>
    from torch_geometric.data import InMemoryDataset, DataLoader
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch_sparse\__init__.py", line 12, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "D:\Anaconda3\envs\geometric\lib\site-packages\torch\_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "D:\Anaconda3\envs\geometric\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Anaconda3\envs\geometric\Lib\site-packages\torch_sparse\_convert.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by thinng** [comment]
I guess you are running Windows and the trouble could be at loading CDLL (This looks relevant: https://stackoverflow.com/questions/34607082/cannot-load-dll-in-python-with-ctypes). 

The code is running well in Linux.

**Comment by ywj66hh** [comment]
D:\Anaconda33\envs\clcrn\python.exe C:\Users\ywj\PycharmProjects\CLCRN-main\train_clcrn.py 
Traceback (most recent call last):
  File "C:\Users\ywj\PycharmProjects\CLCRN-main\train_clcrn.py", line 7, in <module>
    from supervisor import Supervisor
  File "C:\Users\ywj\PycharmProjects\CLCRN-main\supervisor.py", line 7, in <module>
    from experiments import dataloader
  File "C:\Users\ywj\PycharmProjects\CLCRN-main\experiments\dataloader.py", line 12, in <module>
    from model.manifold.sphere import Sphere
  File "C:\Users\ywj\PycharmProjects\CLCRN-main\model\manifold\sphere.py", line 5, in <module>
    import torch_scatter 
  File "D:\Anaconda33\envs\clcrn\lib\site-packages\torch_scatter\__init__.py", line 13, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "D:\Anaconda33\envs\clcrn\lib\site-packages\torch\_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "D:\Anaconda33\envs\clcrn\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Anaconda33\envs\clcrn\Lib\site-packages\torch_scatter\_scatter_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
